// Validate tinyvdb's NanoVDB Root→Upper→Lower→Leaf accessor against
// libopenvdb-produced reference .nvdb files.
//
// Reference .nvdb files are generated by:
//   nanovdb_convert -f data/reference/ref_float.vdb \
//     data/reference_nvdb/ref_float.nvdb
//
// (And likewise ref_double.) Both are 4x4x4 = 64 active voxels with the
// same value pattern as gen_openvdb_reference.cc:
//   float:  v = idx*0.125 - 1
//   double: v = idx*0.125 - 1
//   idx = z*16 + y*4 + x
//
// Skips with exit 0 if the corpus is absent (the .nvdb files are
// gitignored and only present after running nanovdb_convert).

#include "tinyvdb_nanovdb.h"

#include <math.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>

static int check_float(const char *path) {
    tvdb_nanovdb_file_t f; memset(&f, 0, sizeof(f));
    tvdb_error_t err = {0};
    if (tvdb_nanovdb_file_open(&f, path, NULL, &err) != TVDB_OK) {
        fprintf(stderr, "FAIL: open %s: %s\n", path, err.message);
        return 1;
    }
    if (f.grid_count == 0) {
        fprintf(stderr, "FAIL: %s has no grids\n", path);
        tvdb_nanovdb_file_close(&f);
        return 1;
    }
    const tvdb_nanovdb_grid_t *g = &f.grids[0];
    if (g->grid_type != TVDB_NANOVDB_GRID_TYPE_FLOAT) {
        fprintf(stderr, "FAIL: %s expected Float, got %s\n", path,
                tvdb_nanovdb_grid_type_name(g->grid_type));
        tvdb_nanovdb_file_close(&f);
        return 1;
    }

    int errors = 0;
    for (int z = 0; z < 4; ++z) {
        for (int y = 0; y < 4; ++y) {
            for (int x = 0; x < 4; ++x) {
                int idx = z * 16 + y * 4 + x;
                float expected = (float)idx * 0.125f - 1.0f;
                float got = tvdb_nanovdb_get_voxel_f(g, x, y, z);
                if (fabsf(got - expected) > 1e-6f) {
                    if (errors < 5) {
                        fprintf(stderr, "FAIL [%s]: voxel(%d,%d,%d) "
                                "expected %g got %g\n",
                                path, x, y, z, expected, got);
                    }
                    ++errors;
                }
            }
        }
    }

    /* Trilinear sample at cell-center should equal the voxel value. */
    float s = tvdb_nanovdb_sample_trilinear_f(g, 1.5f, 2.5f, 3.5f);
    float exp = (3 * 16 + 2 * 4 + 1) * 0.125f - 1.0f;
    if (fabsf(s - exp) > 1e-5f) {
        fprintf(stderr, "FAIL [%s]: sample(1.5,2.5,3.5)=%g expected %g\n",
                path, s, exp);
        ++errors;
    }

    /* Trilinear sample halfway between two voxels should be their mean. */
    s = tvdb_nanovdb_sample_trilinear_f(g, 1.0f, 0.5f, 0.5f);
    /* Halfway in x between voxels (0,0,0)=−1 and (1,0,0)=−0.875. */
    float halfway = ((0 * 0.125f - 1.0f) + (1 * 0.125f - 1.0f)) * 0.5f;
    if (fabsf(s - halfway) > 1e-5f) {
        fprintf(stderr, "FAIL [%s]: sample(1,0.5,0.5)=%g expected %g\n",
                path, s, halfway);
        ++errors;
    }

    if (errors == 0) {
        printf("[ok] %s: 64 float voxels match, trilinear sample exact at "
               "cell-center, midpoint interp correct\n", path);
    }
    tvdb_nanovdb_file_close(&f);
    return errors ? 1 : 0;
}

static int check_double(const char *path) {
    tvdb_nanovdb_file_t f; memset(&f, 0, sizeof(f));
    tvdb_error_t err = {0};
    if (tvdb_nanovdb_file_open(&f, path, NULL, &err) != TVDB_OK) {
        fprintf(stderr, "FAIL: open %s: %s\n", path, err.message);
        return 1;
    }
    if (f.grid_count == 0) {
        fprintf(stderr, "FAIL: %s has no grids\n", path);
        tvdb_nanovdb_file_close(&f);
        return 1;
    }
    const tvdb_nanovdb_grid_t *g = &f.grids[0];
    if (g->grid_type != TVDB_NANOVDB_GRID_TYPE_DOUBLE) {
        fprintf(stderr, "FAIL: %s expected Double, got %s\n", path,
                tvdb_nanovdb_grid_type_name(g->grid_type));
        tvdb_nanovdb_file_close(&f);
        return 1;
    }

    int errors = 0;
    for (int z = 0; z < 4; ++z) {
        for (int y = 0; y < 4; ++y) {
            for (int x = 0; x < 4; ++x) {
                int idx = z * 16 + y * 4 + x;
                double expected = (double)idx * 0.125 - 1.0;
                double got = tvdb_nanovdb_get_voxel_d(g, x, y, z);
                if (fabs(got - expected) > 1e-12) {
                    if (errors < 5) {
                        fprintf(stderr, "FAIL [%s]: voxel(%d,%d,%d) "
                                "expected %g got %g\n",
                                path, x, y, z, expected, got);
                    }
                    ++errors;
                }
            }
        }
    }
    if (errors == 0) {
        printf("[ok] %s: 64 double voxels match\n", path);
    }
    tvdb_nanovdb_file_close(&f);
    return errors ? 1 : 0;
}

int main(int argc, char **argv) {
    const char *root = argc > 1 ? argv[1] : "..";

    char ff[512], fd[512];
    snprintf(ff, sizeof(ff), "%s/data/reference_nvdb/ref_float.nvdb", root);
    snprintf(fd, sizeof(fd), "%s/data/reference_nvdb/ref_double.nvdb", root);

    struct stat st;
    if (stat(ff, &st) != 0) {
        printf("[skip] reference NanoVDB corpus not present at "
               "%s/data/reference_nvdb/\n", root);
        printf("       regenerate via: nanovdb_convert -f "
               "data/reference/ref_float.vdb data/reference_nvdb/ref_float.nvdb\n");
        return 0;
    }

    int fails = 0;
    fails += check_float(ff);
    fails += check_double(fd);
    if (fails) {
        fprintf(stderr, "%d FAILURES\n", fails);
        return 1;
    }
    printf("All NanoVDB reference checks passed.\n");
    return 0;
}
